In [26]:
import pandas as pd
import pdfplumber

In [27]:
PDF_FILE_PATH = "ayurveda.pdf"

In [28]:
XLS_FILE_PATH = "ayurveda.xls"

In [29]:
def extract_pdf(pdf_path):
    data = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            tables = page.extract_tables()
            for table in tables:
                for row in table:
                    if any(row):  # skip empty rows
                        data.append(row)
    return data

In [30]:
extracted_data = extract_pdf(PDF_FILE_PATH)
len(extracted_data)

1582

In [31]:
tableHead = ['Term ID',
  'English term',
  'Description',
  'Sanskrit term in IAST*',
  'Sanskrit term']

In [32]:
while tableHead in extracted_data:
    extracted_data.remove(tableHead)

In [33]:
len(extracted_data)

1337

In [34]:
ayurveda_df = pd.DataFrame(extracted_data, columns=["Term ID", "English term", "Description", "Sanskrit (IAST)", "Sanskrit"])

In [11]:
ayurveda_df

,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,5.1,Disorder,,,
1,ITA-5.1.1,Disorder,A disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
2,5.2,Derangement of dosha,,,
3,ITA-5.2.1,Derangement\nof dosha,,doṣavaiṣamyam,दोषर्ैषमयम्
4,ITA-5.2.2,State of dosha,,doṣāvasthā,दोषार्सरा
...,...,...,...,...,...
1332,ITA-5.76.236,Condition due to\nusage of very\nunctuous wick...,A condition characterized by increased moistne...,atisnigdhavraṇavarti-\nupayogaḥ,अवतवनिगधव्रणर्रतवा-उपयोगः
1333,ITA-5.76.237,Condition due to\ntightly packed or\nbandaged ...,A condition characterized characterized by oed...,gāḍhabandhana-vraṇaḥ,गाढबनधि-व्रणः
1334,ITA-5.76.238,Condition due to\nimproper management\nof woun...,,mithyāvraṇopacāraḥ,वमथयाव्रणोपिािः
1335,ITA-5.76.239,Condition due to\nimproper intake of\nastringe...,,kaṣāyarasa-mithyāyogaḥ,्कषायिस-वमथयायोगः
1336,ITA-5.76.240,Condition due to use of\ngruel endstage of fever,,yūṣopayogajīrṇajvaraḥ,यूषोपयोगजीणवाजर्िः/\nयूषोपयोगर्ातजर्िः

In [12]:
ayurveda_df.drop(columns=["Term ID"], inplace=True)

In [13]:
ayurveda_df = ayurveda_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

/tmp/ipykernel_292421/309496769.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ayurveda_df = ayurveda_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [14]:
ayurveda_df

,English term,Description,Sanskrit (IAST),Sanskrit
0,disorder,,,
1,disorder,a disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
2,derangement of dosha,,,
3,derangement\nof dosha,,doṣavaiṣamyam,दोषर्ैषमयम्
4,state of dosha,,doṣāvasthā,दोषार्सरा
...,...,...,...,...
1332,condition due to\nusage of very\nunctuous wick...,a condition characterized by increased moistne...,atisnigdhavraṇavarti-\nupayogaḥ,अवतवनिगधव्रणर्रतवा-उपयोगः
1333,condition due to\ntightly packed or\nbandaged ...,a condition characterized characterized by oed...,gāḍhabandhana-vraṇaḥ,गाढबनधि-व्रणः
1334,condition due to\nimproper management\nof woun...,,mithyāvraṇopacāraḥ,वमथयाव्रणोपिािः
1335,condition due to\nimproper intake of\nastringe...,,kaṣāyarasa-mithyāyogaḥ,्कषायिस-वमथयायोगः
1336,condition due to use of\ngruel endstage of fever,,yūṣopayogajīrṇajvaraḥ,यूषोपयोगजीणवाजर्िः/\nयूषोपयोगर्ातजर्िः

## Reading NAMASTE

In [35]:
ayurveda_namaste = pd.read_excel('ayurveda.xls')

In [36]:
ayurveda_namaste.drop(columns=['Sr No.'])

,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches
0,1,AYU,vyAdhi-viniScayaH,vyādhi-viniścayaḥ,व्याधि-विनिश्चयः,NaN,NaN,NaN
1,2,DIS,vikAraH,vikāraḥ,विकारः,NaN,NaN,NaN
2,3,A,doShavaiShamyam,dōṣavaiṣamyam,दोषवैषम्यम्,NaN,NaN,NaN
3,4,AA,vAtavyAdhiH,vātavyādhiḥ,वातव्याधिः,NaN,NaN,NaN
4,5,AAA,doShAvasthA (vAta),dōṣāvasthā (vāta),दोषावस्था (वात),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2888,2984,EJ-4.11,NaN,vṛkkarogaḥ,वृक्करोगः,NaN,"The disorder is characterized by vomiting, ed...",NaN
2889,2985,EJ-4.11.1,NaN,vṛkkarogaḥ-pūrvarupam,वृक्करोगः-पूर्वरुपम्,NaN,The disorder is characterized by signs and sym...,NaN
2890,2986,EJ-4.11.2,NaN,vṛkkarogaḥ-upadravaḥ,वृक्करोगः-उपद्रवः,NaN,The disorder is characterized by implications ...,NaN
2891,2987,VH-5,svastha,svastha,स्वस्थ,NaN,"An individual in a balanced state of dosha, me...",NaN
2892,2988,GGGGGQ,GGGGQ,GGGGQ,GGGQ,QGGGGQ,GGGQ,GGGQ

In [37]:
cols_to_clean = ["NAMC_term","NAMC_term_diacritical", "NAMC_term_DEVANAGARI"]

for col in cols_to_clean:
    ayurveda_namaste[col] = ayurveda_namaste[col].astype(str).str.replace(r"\(.*?\)", "", regex=True).str.strip()

In [38]:
ayurveda_namaste = ayurveda_namaste.applymap(lambda x: x.lower() if isinstance(x, str) else x)

/tmp/ipykernel_292421/4211374912.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ayurveda_namaste = ayurveda_namaste.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [39]:
ayurveda_namaste

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches
0,1,1,ayu,vyadhi-viniscayah,vyādhi-viniścayaḥ,व्याधि-विनिश्चयः,NaN,NaN,NaN
1,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN
2,3,3,a,doshavaishamyam,dōṣavaiṣamyam,दोषवैषम्यम्,NaN,NaN,NaN
3,4,4,aa,vatavyadhih,vātavyādhiḥ,वातव्याधिः,NaN,NaN,NaN
4,5,5,aaa,doshavastha,dōṣāvasthā,दोषावस्था,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2888,2889,2984,ej-4.11,nan,vṛkkarogaḥ,वृक्करोगः,NaN,"the disorder is characterized by vomiting, ed...",NaN
2889,2890,2985,ej-4.11.1,nan,vṛkkarogaḥ-pūrvarupam,वृक्करोगः-पूर्वरुपम्,NaN,the disorder is characterized by signs and sym...,NaN
2890,2891,2986,ej-4.11.2,nan,vṛkkarogaḥ-upadravaḥ,वृक्करोगः-उपद्रवः,NaN,the disorder is characterized by implications ...,NaN
2891,2892,2987,vh-5,svastha,svastha,स्वस्थ,NaN,"an individual in a balanced state of dosha, me...",NaN
2892,2893,2988,gggggq,ggggq,ggggq,gggq,qggggq,gggq,gggq

In [45]:
merged_df = pd.merge(
    ayurveda_namaste,
    ayurveda_df,
    left_on='NAMC_term_diacritical',
    right_on='Sanskrit (IAST)',
    how='left'
)

In [68]:
merged_df4 = pd.merge(
    ayurveda_namaste,
    ayurveda_df,
    left_on='NAMC_term',
    right_on='Sanskrit (IAST)',
    how='left'
)

In [70]:
filtered_df4 = merged_df4[merged_df4['Term ID'].notna()].reset_index(drop=True)

In [71]:
filtered_df4

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,292,295,abb-34,raktapittam,raktapittam,रक्तपित्तम्,NaN,NaN,NaN,ITA-5.16.1,Haemorrhage from\nexternal and internal\norifi...,A disorder characterized by some or all the fo...,raktapittam,ि्तवप्तम्
1,547,558,sm39(eb-4),amlapittam,amlapittam,अम्लपित्तम्,NaN,"it is characterised by indigestion, burning se...",NaN,ITA-5.33.1,Hyperacidity,A disorder characterized by some or all the fo...,amlapittam,अमलवप्तम्
2,908,944,sl81(ed-7),raktapittam,raktapittam,रक्तपित्तम्,NaN,it is characterised by bleeding from body orif...,note: also classifed under #san@sonitajanyarog...,ITA-5.16.1,Haemorrhage from\nexternal and internal\norifi...,A disorder characterized by some or all the fo...,raktapittam,ि्तवप्तम्
3,914,950,ed-7.6,pittajaraktapittam,pittajaraktapittam,पित्तजरक्तपित्तम्,NaN,the disorder is characterized by kaṣāyābha-rak...,NaN,ITA-5.16.3,Haemorrhage due to\npredominance of pitta,A disorder characterized by some or all the fo...,pittajaraktapittam,वप्तजि्तवप्तम्
4,1572,1634,gf-11 (sl03),svaraghnam,svaraghnam,स्वरघ्नम्,NaN,NaN,NaN,ITA-5.63.67,Paralysis of vocal\ncords,A disorder characterized by some or all the fo...,svaraghnam,सर्िघ्नम्
5,1631,1697,hb-8 (sk7y),bahalavartma,bahalavartma,बहलवर्त्म,NaN,NaN,NaN,ITA-5.66.77,Multiple\nMeibomian cysts,A disorder characterized by the whole eyelid b...,bahalavartma,बिलर्तमवा
6,1643,1709,hb-20,bisavartma,nan,बिसवर्त्म,NaN,NaN,NaN,ITA-5.66.89,Ulcerative\nconjunctivitis,A disorder characterized by external swelling;...,bisavartma,वबसर्तमवा
7,1904,1975,la-1.3,vivartita-sandhimuktam,vivartita-sandhimuktam,विवर्तित-सन्धिमुक्तम्,NaN,the disorder is characterized by sandhipārśvāp...,NaN,ITA-5.55.4,Dislocation with\nlateral displacement,A lateral dislocation of a joint characterized...,vivartita-sandhimuktam,वर्र्रतवात-सवनधमु्तम्
8,1944,2015,lb-1.2,durdagdham,durdagdham,दुर्दग्धम्,NaN,the disorder is characterized by sphōṭaḥ [blis...,NaN,ITA-5.76.230,Improper burn,A condition characterized by some or all the f...,durdagdham,ददु गवा धम्
9,2754,2846,su-1.2,durdagdham,durdagdham,दुर्दग्धम्,NaN,the disorder is characterized by sphōṭāḥ [blis...,NaN,ITA-5.76.230,Improper burn,A condition characterized by some or all the f...,durdagdham,ददु गवा धम्

In [46]:
merged_df

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,1,1,ayu,vyadhi-viniscayah,vyādhi-viniścayaḥ,व्याधि-विनिश्चयः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN,ITA-5.1.1,Disorder,A disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
2,3,3,a,doshavaishamyam,dōṣavaiṣamyam,दोषवैषम्यम्,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,aa,vatavyadhih,vātavyādhiḥ,वातव्याधिः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,aaa,doshavastha,dōṣāvasthā,दोषावस्था,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,2889,2984,ej-4.11,nan,vṛkkarogaḥ,वृक्करोगः,NaN,"the disorder is characterized by vomiting, ed...",NaN,NaN,NaN,NaN,NaN,NaN
2892,2890,2985,ej-4.11.1,nan,vṛkkarogaḥ-pūrvarupam,वृक्करोगः-पूर्वरुपम्,NaN,the disorder is characterized by signs and sym...,NaN,NaN,NaN,NaN,NaN,NaN
2893,2891,2986,ej-4.11.2,nan,vṛkkarogaḥ-upadravaḥ,वृक्करोगः-उपद्रवः,NaN,the disorder is characterized by implications ...,NaN,NaN,NaN,NaN,NaN,NaN
2894,2892,2987,vh-5,svastha,svastha,स्वस्थ,NaN,"an individual in a balanced state of dosha, me...",NaN,NaN,NaN,NaN,NaN,NaN
2895,2893,2988,gggggq,ggggq,ggggq,gggq,qggggq,gggq,gggq,NaN,NaN,NaN,NaN,NaN

In [47]:
len(merged_df)

2896

In [50]:
# Keep only rows where 'Term ID' is not NaN
filtered_df = merged_df[merged_df['Term ID'].notna()].reset_index(drop=True)

In [51]:
filtered_df

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN,ITA-5.1.1,Disorder,A disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
1,6,6,sr11 (aaa-1),vatasa~jcayah,vātasañcayaḥ,वातसञ्चयः,NaN,it is characterized by impaired movements of v...,NaN,ITA-5.2.1.1,Accumulation of vata,A disorder characterized by impaired movements...,vātasañcayaḥ,र्ातसञ्यः
2,15,15,sr14 (aaa-4),vatakshayah,vātakṣayaḥ,वातक्षयः,NaN,it is characterized by sluggishness in activit...,NaN,ITA-5.2.1.9,Diminution of vata,A disorder characterized by some or all the fo...,vātakṣayaḥ,र्ातक्षयः
3,22,22,aab-6,arditah,arditaḥ,अर्दितः,NaN,NaN,NaN,ITA-5.2.1.33,Facial paralysis,A disorder characterized by localized paralysi...,arditaḥ,अरदवातः
4,33,33,aab-17,udavartah,udāvartaḥ,उदावर्तः,NaN,NaN,NaN,ITA-5.35.1,Disorders of reversed\nor altered visceral\nmo...,A disorder characterized by some or all the fo...,udāvartaḥ,उदार्तवाः
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,2748,2840,su,agnikarma-apacarah,agnikarma-apacāraḥ,अग्निकर्म-अपचारः,NaN,NaN,NaN,ITA-5.76.224,Condition due to\ndue to improper\napplication...,,agnikarma-apacāraḥ,अव्न्कमवा-अपिािः
465,2750,2842,su-1.1,agni-atidagdhah,agni-atidagdhaḥ,अग्नि-अतिदग्धः,NaN,the disorder is characterized by māṁsāvalamban...,NaN,ITA-5.76.226,Condition due to\nexcessive burns due\nto ther...,A condition characterized by some or all the f...,agni-atidagdhaḥ,अव्न-अवतदगधः
466,2753,2845,su-1.1.3,atidagdha-arsah,atidagdha-arśaḥ,अतिदग्ध-अर्शः,NaN,the disorder is characterized by gudāvadaraṇam...,NaN,ITA-5.76.229,Condition due to\nexcessive cautery of\nhaemor...,A condition characterized by some or all the f...,atidagdha-arśaḥ,अवतदगध-अशवाः
467,2754,2846,su-1.2,durdagdham,durdagdham,दुर्दग्धम्,NaN,the disorder is characterized by sphōṭāḥ [blis...,NaN,ITA-5.76.230,Improper burn,A condition characterized by some or all the f...,durdagdham,ददु गवा धम्
468,2755,2847,su-1.3,hinadagdha-arsah,hīnadagdha-arśaḥ,हीनदग्ध-अर्शः,NaN,the disorder is characterized by dhyāmavraṇaḥ ...,NaN,ITA-5.76.231,Condition due to\ninadequate cautery\nof haemo...,A condition characterized by some or all the f...,hīnadagdha-arśaḥ,िीिदगध-अशवाः

In [53]:
len(filtered_df)

469

In [54]:
filtered_df.to_csv("IAST_Equivalnce_Matching.csv")

In [55]:
merged_df2 = pd.merge(
    ayurveda_namaste,
    ayurveda_df,
    left_on='NAMC_term_DEVANAGARI',
    right_on='Sanskrit',
    how='left'
)

In [56]:
merged_df2

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,1,1,ayu,vyadhi-viniscayah,vyādhi-viniścayaḥ,व्याधि-विनिश्चयः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,a,doshavaishamyam,dōṣavaiṣamyam,दोषवैषम्यम्,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,aa,vatavyadhih,vātavyādhiḥ,वातव्याधिः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,aaa,doshavastha,dōṣāvasthā,दोषावस्था,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,2889,2984,ej-4.11,nan,vṛkkarogaḥ,वृक्करोगः,NaN,"the disorder is characterized by vomiting, ed...",NaN,NaN,NaN,NaN,NaN,NaN
2889,2890,2985,ej-4.11.1,nan,vṛkkarogaḥ-pūrvarupam,वृक्करोगः-पूर्वरुपम्,NaN,the disorder is characterized by signs and sym...,NaN,NaN,NaN,NaN,NaN,NaN
2890,2891,2986,ej-4.11.2,nan,vṛkkarogaḥ-upadravaḥ,वृक्करोगः-उपद्रवः,NaN,the disorder is characterized by implications ...,NaN,NaN,NaN,NaN,NaN,NaN
2891,2892,2987,vh-5,svastha,svastha,स्वस्थ,NaN,"an individual in a balanced state of dosha, me...",NaN,NaN,NaN,NaN,NaN,NaN
2892,2893,2988,gggggq,ggggq,ggggq,gggq,qggggq,gggq,gggq,NaN,NaN,NaN,NaN,NaN

In [57]:
filtered_df2 = merged_df2[merged_df2['Term ID'].notna()].reset_index(drop=True)

In [58]:
filtered_df2

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,53,53,aab-37,grudhrasi,gr̥dhrasī,गृध्रसी,NaN,the disorder is characterized by kramāt sphik-...,NaN,ITA-5.2.1.38,Sciatica,A disorder characterized by some or all the fo...,gṛdhrasī,गृध्रसी
1,143,145,aac-10(sp2y ),amsasoshah,aṃsaśoṣaḥ,अंसशोषः,NaN,NaN,NaN,ITA-5.2.1.47,Muscle wasting around\nshoulder joint,A disorder characterized by atrophy of structu...,aṃsaśoṣaḥ,अंसशोषः
2,155,157,sp41(aac-20),grudhrasi,gṛdhrasī,गृध्रसी,NaN,it is characterised by moderate to severe pain...,NaN,ITA-5.2.1.38,Sciatica,A disorder characterized by some or all the fo...,gṛdhrasī,गृध्रसी
3,392,395,sr46(bc-1),mamsakshayah,māṃsakṣayaḥ,मांसक्षयः,NaN,"it is characterized by wasting of hips, wastin...",NaN,ITA-5.3.13,Diminution of muscle,A disorder characterized by some or all the fo...,māmsakṣayaḥ,मांसक्षयः
4,395,398,sr48(bd-1),medahkshayah,medaḥkṣayaḥ,मेदःक्षयः,NaN,"it is characterized by breaking, splitting typ...",NaN,ITA-5.3.16,Diminution of fat,A disorder characterized by some or all the fo...,medaḥkṣayaḥ,मेदःक्षयः
5,413,416,sr4f(bh-1),ojakshayah,ojaḥkṣayaḥ,ओजक्षयः,NaN,"it is characterized by fear, loss of physical ...",NaN,ITA-5.3.34,Diminution of ojas,A disorder characterized by some or all the fo...,ojakṣayaḥ,ओजक्षयः
6,448,452,sr86(cb-3),svedavaishamyam,sāmamalaḥ,साममलः,NaN,it is characterized by obstruction in channels...,NaN,ITA-5.4.8,Excretory products\nassociated with\nincomplet...,A disorder characterized by some or all the fo...,sāmamalaḥ,साममलः
7,619,633,sm33(eb-10),sulah,śūlaḥ,शूलः,NaN,"it is characterised by pain in abdomen, burnin...",NaN,ITA-5.34.1,Abdominal colic,A disorder characterized by pain in abdomen; p...,śūlaḥ,शूलः
8,624,638,eb-10.5,amasulah,āmaśūlaḥ,आमशूलः,NaN,the disorder is characterized by āṭōpaḥ [gurgl...,NaN,ITA-5.34.6,Abdominal colic\ndue to āma,A disorder characterized by some or all the fo...,āmaśūlaḥ,आमशूलः
9,629,643,sm3d(eb-10.10),parinamasulah,pariṇāmaśūlaḥ,परिणामशूलः,NaN,it is characterised by stabbing or piercing pa...,NaN,ITA-5.34.9,Abdominal colic\noccurring during\ndigestion o...,,pariṇāmaśūlaḥ,परिणामशूलः
10,667,681,sl61(ec-2),hrudrogah,hṛdrogaḥ,हृद्रोगः,NaN,"it is characterised by chest pain, discomfort,...",NaN,ITA-5.38.1,Heart disease,,hṛdrogaḥ,हृद्रोगः
11,987,1024,sm01 (ed-13),slipadah,ślīpadaḥ,श्लीपदः,NaN,it is characterised by a disorder characterise...,NaN,ITA-5.51.1,Filariasis,A disorder characterized by some or all the fo...,ślīpadaḥ,श्लीपदः
12,1267,1314,ek-3.10,amasopah,āmaśōphaḥ,आमशोफः,NaN,the disorder is characterized by alpaśōthatvam...,NaN,ITA-5.73.11,"Unripe swelling,\npre-pus formation\nstage.",A disorder characterized by reduced swelling; ...,āmaśophaḥ,आमशोफः
13,1358,1416,el-8.4,parighah,parighaḥ,परिघः,NaN,the disorder is characterized by parigha iva y...,NaN,ITA-5.70.7,Obstructed fetal\npresentation with fetus\nin ...,Abnormal fetal presentation characterized by a...,parighaḥ,परिघः
14,1506,1566,gb-1 (sm1y),sitadah,śītādaḥ,शीतादः,NaN,NaN,NaN,ITA-5.63.11,Spongy gums,A disorder characterized by some or all the fo...,śītādaḥ,शीतादः
15,1546,1607,sm17 (ge-4),adhrushah,adhruṣaḥ,अध्रुषः,NaN,"it is characterised by pain, swelling and redn...",NaN,ITA-5.63.41,Acute inflammation\nof soft palate,A disorder characterized by some or all the fo...,adhruṣaḥ,अध्रुषः
16,1551,1612,ge-9,talusoshah,nan,तालुशोषः,NaN,NaN,NaN,ITA-5.63.46,Atrophy of palate,A disorder characterized by excessive dryness ...,tāluśoṣaḥ,तालुशोषः
17,1565,1627,sl05 (gf-4),balasah,balāsaḥ,बलासः,NaN,"it is characterised by pain, swelling redness ...",NaN,ITA-5.63.60,Inflammatory\nswelling of throat,A disorder characterized by some or all the fo...,balāsaḥ,बलासः
18,1568,1630,sl01 (gf-7),sataghni,śataghnī,शतघ्नी,NaN,"it is characterised by suppurative growth, pai...",NaN,ITA-5.63.63,Retro-pharyngeal\nabscess,A disorder characterized by some or all the fo...,śataghnī,शतघ्नी
19,1571,1633,gf-10 (sl05),galaughah,galaughaḥ,गलौघः,NaN,NaN,NaN,ITA-5.63.66,Acute inflammation\nof hypopharyngeal\nregion,A disorder characterized by some or all the fo...,galaughaḥ,गलौघः
20,1612,1678,sk68 (ha-1),puyalasah,pūyālasaḥ,पूयालसः,NaN,it is characterised by swelling over medial ca...,NaN,ITA-5.66.58,Acute dacrocystitis,A disorder characterized by a swelling over th...,pūyālasaḥ,पूयालसः
21,1621,1687,ha-5 (sk7y),alaji,alajī,अलजी,NaN,NaN,NaN,ITA-5.66.67,Phlyctenular kerato-\nconjuctivitis,A disorder characterized by some or all the fo...,alajī,अलजी
22,1642,1708,sk6n (hb-19),laganah,lagaṇaḥ,लगणः,NaN,it is characterised by big hard painless movab...,NaN,ITA-5.66.88,Chalazion,A disorder characterized by a non-suppurating;...,lagaṇaḥ,लगणः
23,1712,1779,hg-2.1,trutiyapatalagata-doshah,nan,तृतीयपटलगत-दोषः,NaN,NaN,NaN,ITA-5.66.28,Disorder affecting\nthird layer of eye,A disorder characterized by some or all the fo...,tṛtīyapaṭalagata-doṣaḥ,तृतीयपटलगत-दोषः
24,1845,1913,sn4w (k),vranah,vraṇaḥ,व्रणः,NaN,it is characterised by discountinuity of struc...,NaN,ITA-5.54.1,Ulcer,An ulcer is an open sore on an external or int...,vraṇaḥ,व्रणः
25,1846,1914,sp5a (ka),vranasopah,vraṇaśophaḥ,व्रणशोफः,NaN,it is characterised by swelling with yellowish...,NaN,ITA-5.53.1,Pre-ulcerative\ninflammation,A condition characterized by widespread or nod...,vraṇaśophaḥ,व्रणशोफः
26,1880,1951,k-4,ruhyamanavranah,ruhyamāṇavraṇaḥ,रुह्यमाणव्रणः,NaN,the disorder is characterized by kapōtavarṇapr...,NaN,ITA-5.54.9,Healing ulcer,An ulcer characterized by pigeon-coloured marg...,ruhyamāṇavraṇaḥ,रुह्यमाणव्रणः
27,2163,2242,sn48 (o-6),alasah,alasaḥ,अलसः,NaN,"it is characterised by sticky moistness, itchi...",NaN,ITA-5.62.24,Lesion of interdigital\nclefts of feet,A disorder characterized by pain in the interd...,alasaḥ,अलसः

In [72]:
concat = pd.concat([filtered_df, filtered_df2,filtered_df4], ignore_index=True)

In [73]:
concat

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN,ITA-5.1.1,Disorder,A disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
1,6,6,sr11 (aaa-1),vatasa~jcayah,vātasañcayaḥ,वातसञ्चयः,NaN,it is characterized by impaired movements of v...,NaN,ITA-5.2.1.1,Accumulation of vata,A disorder characterized by impaired movements...,vātasañcayaḥ,र्ातसञ्यः
2,15,15,sr14 (aaa-4),vatakshayah,vātakṣayaḥ,वातक्षयः,NaN,it is characterized by sluggishness in activit...,NaN,ITA-5.2.1.9,Diminution of vata,A disorder characterized by some or all the fo...,vātakṣayaḥ,र्ातक्षयः
3,22,22,aab-6,arditah,arditaḥ,अर्दितः,NaN,NaN,NaN,ITA-5.2.1.33,Facial paralysis,A disorder characterized by localized paralysi...,arditaḥ,अरदवातः
4,33,33,aab-17,udavartah,udāvartaḥ,उदावर्तः,NaN,NaN,NaN,ITA-5.35.1,Disorders of reversed\nor altered visceral\nmo...,A disorder characterized by some or all the fo...,udāvartaḥ,उदार्तवाः
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,1631,1697,hb-8 (sk7y),bahalavartma,bahalavartma,बहलवर्त्म,NaN,NaN,NaN,ITA-5.66.77,Multiple\nMeibomian cysts,A disorder characterized by the whole eyelid b...,bahalavartma,बिलर्तमवा
503,1643,1709,hb-20,bisavartma,nan,बिसवर्त्म,NaN,NaN,NaN,ITA-5.66.89,Ulcerative\nconjunctivitis,A disorder characterized by external swelling;...,bisavartma,वबसर्तमवा
504,1904,1975,la-1.3,vivartita-sandhimuktam,vivartita-sandhimuktam,विवर्तित-सन्धिमुक्तम्,NaN,the disorder is characterized by sandhipārśvāp...,NaN,ITA-5.55.4,Dislocation with\nlateral displacement,A lateral dislocation of a joint characterized...,vivartita-sandhimuktam,वर्र्रतवात-सवनधमु्तम्
505,1944,2015,lb-1.2,durdagdham,durdagdham,दुर्दग्धम्,NaN,the disorder is characterized by sphōṭaḥ [blis...,NaN,ITA-5.76.230,Improper burn,A condition characterized by some or all the f...,durdagdham,ददु गवा धम्
506,2754,2846,su-1.2,durdagdham,durdagdham,दुर्दग्धम्,NaN,the disorder is characterized by sphōṭāḥ [blis...,NaN,ITA-5.76.230,Improper burn,A condition characterized by some or all the f...,durdagdham,ददु गवा धम्

In [74]:
concat.drop_duplicates(subset="NAMC_ID",keep="first")

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,2,2,dis,vikarah,vikāraḥ,विकारः,NaN,NaN,NaN,ITA-5.1.1,Disorder,A disorder refers to a set of dysfunctions in ...,vikāraḥ,वर््कािः
1,6,6,sr11 (aaa-1),vatasa~jcayah,vātasañcayaḥ,वातसञ्चयः,NaN,it is characterized by impaired movements of v...,NaN,ITA-5.2.1.1,Accumulation of vata,A disorder characterized by impaired movements...,vātasañcayaḥ,र्ातसञ्यः
2,15,15,sr14 (aaa-4),vatakshayah,vātakṣayaḥ,वातक्षयः,NaN,it is characterized by sluggishness in activit...,NaN,ITA-5.2.1.9,Diminution of vata,A disorder characterized by some or all the fo...,vātakṣayaḥ,र्ातक्षयः
3,22,22,aab-6,arditah,arditaḥ,अर्दितः,NaN,NaN,NaN,ITA-5.2.1.33,Facial paralysis,A disorder characterized by localized paralysi...,arditaḥ,अरदवातः
4,33,33,aab-17,udavartah,udāvartaḥ,उदावर्तः,NaN,NaN,NaN,ITA-5.35.1,Disorders of reversed\nor altered visceral\nmo...,A disorder characterized by some or all the fo...,udāvartaḥ,उदार्तवाः
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,1712,1779,hg-2.1,trutiyapatalagata-doshah,nan,तृतीयपटलगत-दोषः,NaN,NaN,NaN,ITA-5.66.28,Disorder affecting\nthird layer of eye,A disorder characterized by some or all the fo...,tṛtīyapaṭalagata-doṣaḥ,तृतीयपटलगत-दोषः
493,1845,1913,sn4w (k),vranah,vraṇaḥ,व्रणः,NaN,it is characterised by discountinuity of struc...,NaN,ITA-5.54.1,Ulcer,An ulcer is an open sore on an external or int...,vraṇaḥ,व्रणः
494,1846,1914,sp5a (ka),vranasopah,vraṇaśophaḥ,व्रणशोफः,NaN,it is characterised by swelling with yellowish...,NaN,ITA-5.53.1,Pre-ulcerative\ninflammation,A condition characterized by widespread or nod...,vraṇaśophaḥ,व्रणशोफः
495,1880,1951,k-4,ruhyamanavranah,ruhyamāṇavraṇaḥ,रुह्यमाणव्रणः,NaN,the disorder is characterized by kapōtavarṇapr...,NaN,ITA-5.54.9,Healing ulcer,An ulcer characterized by pigeon-coloured marg...,ruhyamāṇavraṇaḥ,रुह्यमाणव्रणः
503,1643,1709,hb-20,bisavartma,nan,बिसवर्त्म,NaN,NaN,NaN,ITA-5.66.89,Ulcerative\nconjunctivitis,A disorder characterized by external swelling;...,bisavartma,वबसर्तमवा

In [62]:
concat.to_csv("IAST_Sanskrit_Equivalce_Matching.csv")

In [65]:
filtered_df3 = merged_df[merged_df['Term ID'].isna()].reset_index(drop=True)

In [66]:
filtered_df3

,Sr No.,NAMC_ID,NAMC_CODE,NAMC_term,NAMC_term_diacritical,NAMC_term_DEVANAGARI,Short_definition,Long_definition,Ontology_branches,Term ID,English term,Description,Sanskrit (IAST),Sanskrit
0,1,1,ayu,vyadhi-viniscayah,vyādhi-viniścayaḥ,व्याधि-विनिश्चयः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,3,a,doshavaishamyam,dōṣavaiṣamyam,दोषवैषम्यम्,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,4,aa,vatavyadhih,vātavyādhiḥ,वातव्याधिः,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,5,aaa,doshavastha,dōṣāvasthā,दोषावस्था,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,7,sr12 (aaa-2),vatavruddhih,vātavṛddhiḥ,वातवृद्धिः,NaN,it is characterized by roughness or hoarseness...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2422,2889,2984,ej-4.11,nan,vṛkkarogaḥ,वृक्करोगः,NaN,"the disorder is characterized by vomiting, ed...",NaN,NaN,NaN,NaN,NaN,NaN
2423,2890,2985,ej-4.11.1,nan,vṛkkarogaḥ-pūrvarupam,वृक्करोगः-पूर्वरुपम्,NaN,the disorder is characterized by signs and sym...,NaN,NaN,NaN,NaN,NaN,NaN
2424,2891,2986,ej-4.11.2,nan,vṛkkarogaḥ-upadravaḥ,वृक्करोगः-उपद्रवः,NaN,the disorder is characterized by implications ...,NaN,NaN,NaN,NaN,NaN,NaN
2425,2892,2987,vh-5,svastha,svastha,स्वस्थ,NaN,"an individual in a balanced state of dosha, me...",NaN,NaN,NaN,NaN,NaN,NaN
2426,2893,2988,gggggq,ggggq,ggggq,gggq,qggggq,gggq,gggq,NaN,NaN,NaN,NaN,NaN

In [67]:
filtered_df3.to_csv("need_processing.csv")